//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SFO2O.Admin.Service.GetSFData {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ExpressInfoEntity", Namespace="http://schemas.datacontract.org/2004/07/SFO2O.Service.Model.Entity")]
    [System.SerializableAttribute()]
    public partial class ExpressInfoEntity : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AcceptAddressField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime AcceptTimeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MailNoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string OpcodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RemarkField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AcceptAddress {
            get {
                return this.AcceptAddressField;
            }
            set {
                if ((object.ReferenceEquals(this.AcceptAddressField, value) != true)) {
                    this.AcceptAddressField = value;
                    this.RaisePropertyChanged("AcceptAddress");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime AcceptTime {
            get {
                return this.AcceptTimeField;
            }
            set {
                if ((this.AcceptTimeField.Equals(value) != true)) {
                    this.AcceptTimeField = value;
                    this.RaisePropertyChanged("AcceptTime");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MailNo {
            get {
                return this.MailNoField;
            }
            set {
                if ((object.ReferenceEquals(this.MailNoField, value) != true)) {
                    this.MailNoField = value;
                    this.RaisePropertyChanged("MailNo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Opcode {
            get {
                return this.OpcodeField;
            }
            set {
                if ((object.ReferenceEquals(this.OpcodeField, value) != true)) {
                    this.OpcodeField = value;
                    this.RaisePropertyChanged("Opcode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Remark {
            get {
                return this.RemarkField;
            }
            set {
                if ((object.ReferenceEquals(this.RemarkField, value) != true)) {
                    this.RemarkField = value;
                    this.RaisePropertyChanged("Remark");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="GetSFData.IGetSFData")]
    public interface IGetSFData {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGetSFData/GetExpressInfo", ReplyAction="http://tempuri.org/IGetSFData/GetExpressInfoResponse")]
        SFO2O.Admin.Service.GetSFData.ExpressInfoEntity[] GetExpressInfo(string tarcking_number);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGetSFData/GetExpressInfo", ReplyAction="http://tempuri.org/IGetSFData/GetExpressInfoResponse")]
        System.Threading.Tasks.Task<SFO2O.Admin.Service.GetSFData.ExpressInfoEntity[]> GetExpressInfoAsync(string tarcking_number);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGetSFData/QueryIndentity", ReplyAction="http://tempuri.org/IGetSFData/QueryIndentityResponse")]
        int QueryIndentity(string userName, string phone);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGetSFData/QueryIndentity", ReplyAction="http://tempuri.org/IGetSFData/QueryIndentityResponse")]
        System.Threading.Tasks.Task<int> QueryIndentityAsync(string userName, string phone);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IGetSFDataChannel : SFO2O.Admin.Service.GetSFData.IGetSFData, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GetSFDataClient : System.ServiceModel.ClientBase<SFO2O.Admin.Service.GetSFData.IGetSFData>, SFO2O.Admin.Service.GetSFData.IGetSFData {
        
        public GetSFDataClient() {
        }
        
        public GetSFDataClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public GetSFDataClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public GetSFDataClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public GetSFDataClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public SFO2O.Admin.Service.GetSFData.ExpressInfoEntity[] GetExpressInfo(string tarcking_number) {
            return base.Channel.GetExpressInfo(tarcking_number);
        }
        
        public System.Threading.Tasks.Task<SFO2O.Admin.Service.GetSFData.ExpressInfoEntity[]> GetExpressInfoAsync(string tarcking_number) {
            return base.Channel.GetExpressInfoAsync(tarcking_number);
        }
        
        public int QueryIndentity(string userName, string phone) {
            return base.Channel.QueryIndentity(userName, phone);
        }
        
        public System.Threading.Tasks.Task<int> QueryIndentityAsync(string userName, string phone) {
            return base.Channel.QueryIndentityAsync(userName, phone);
        }
    }
}
